spring.application.name=test-task-idf
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/test_task_idf}
spring.datasource.username=${DB_USERNAME:test_task_idf}
spring.datasource.password=${DB_PASSWORD:test_task_idf}
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
springdoc.packages-to-scan=org.example.testtaskidf.controller
spring.jackson.deserialization.fail-on-unknown-properties=true
springdoc.override-with-generic-response=false
exchange-rates.app-id=${OPEN_EXCHANGE_RATES_APP_ID:}
exchange-rates.base-url=${OPEN_EXCHANGE_RATES_BASE_URL:https://openexchangerates.org/api}
exchange-rates.enabled=${EXCHANGE_RATES_ENABLED:true}
exchange-rates.worker-delay-ms=10000
