spring.application.name=test-task-idf
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/test_task_idf}
spring.datasource.username=${DB_USERNAME:test_task_idf}
spring.datasource.password=${DB_PASSWORD:test_task_idf}
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
springdoc.packages-to-scan=org.example.testtaskidf.controller.bank
springdoc.override-with-generic-response=false
